name: Generate LastFM Data

on:
  schedule:
    - cron: "*/18 * * * *" # Run once every 18th minute
  workflow_dispatch: # Make it possible to run manually

permissions:
  contents: write

jobs:
  fetch-lastfm-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone and exit if running between 00:01 and 07:00
        run: |
          export TZ=Europe/Stockholm
          current_hour=$(date +"%H")
          if [ "$current_hour" -ge 0 ] && [ "$current_hour" -lt 7 ]; then
            echo "It's between 00:01 and 07:00 Stockholm/Amsterdam time. Exiting..."
            exit 0
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch recent tracks from LastFM
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        run: |
          # Använd curl för att hämta data från LastFM
          curl "https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=jsongif&api_key=${LASTFM_API_KEY}&format=json&limit=1" \
          -o recent-tracks.json

      - name: Commit and push JSON to repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add recent-tracks.json
          git commit -m "Update recent tracks data"
          git push