name: Generate LastFM Data

on:
  schedule:
    - cron: "*/30 * * * *" # Kör en gång var 30:e minut
  workflow_dispatch: # Gör det möjligt att köra manuellt

jobs:
  fetch-lastfm-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch recent tracks from LastFM
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        run: |
          # Använd curl för att hämta data från LastFM
          curl "https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=ANVÄNDARNAMN_HÄR&api_key=${LASTFM_API_KEY}&format=json" \
          -o recent-tracks.json

      - name: Commit and push JSON to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add recent-tracks.json
          git commit -m "Update recent tracks data"
          git push
